version: '3.8'
networks:
  net:
    driver: bridge
services:
  bot-storemessages:
    image: bot-store-messages:latest
    ports:
      - "8080:8080"   # api
      - "18080:18080" # management
    environment:
      - JAVA_OPTS="-Xmx128m"
      - SPRING_DATA_MONGODB_HOST="host.docker.internal"
      - SPRING_DATA_MONGODB_PORT="27017"
      - SPRING_DATA_MONGODB_USERNAME="root"
      - SPRING_DATA_MONGODB_PASSWORD="root"
      - SPRING_DATA_MONGODB_DATABASE="db_messages"
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE="admin"
      - SPRING_DATA_MONGODB_AUTHENTICATION_MECHANISM="SCRAM-SHA-1"
      - SPRING_RABBITMQ_HOST="host.docker.internal"
      - SPRING_RABBITMQ_PORT="5672"
      - SPRING_RABBITMQ_VIRTUAL_HOST="/"
      - SPRING_RABBITMQ_USERNAME="guest"
      - SPRING_RABBITMQ_PASSWORD="guest"
